// Generated by bench2verilog.py
module multiplier_2_bit(
    A0, A1, B0, B1, P0, P1, P2, P3
);

  input  A0, A1, B0, B1;
  output P0, P1, P2, P3;
  wire   CONST0, CONST1, n_not_A0, n_not_A1, n_not_B0, n_not_B1, p_P0_0, p_P0_1, p_P0_2, p_P0_3, p_P1_0, p_P1_1, p_P1_2, p_P1_3, p_P1_4, p_P1_5, p_P1_6, p_P1_7, p_P1_8, p_P1_9, p_P2_0, p_P2_1, p_P2_10, p_P2_11, p_P2_12, p_P2_2, p_P2_3, p_P2_4, p_P2_5, p_P2_6, p_P2_7, p_P2_8, p_P2_9, p_P3_0;

  assign CONST0 = (A0 & n_not_A0);
  assign CONST1 = (A0 | n_not_A0);
  assign P0 = (p_P0_0 | p_P0_1 | p_P0_2 | p_P0_3);
  assign P1 = (p_P1_0 | p_P1_1 | p_P1_2 | p_P1_3 | p_P1_4 | p_P1_5 | p_P1_6 | p_P1_7 | p_P1_8 | p_P1_9);
  assign P2 = (p_P2_0 | p_P2_1 | p_P2_2 | p_P2_3 | p_P2_4 | p_P2_5 | p_P2_6 | p_P2_7 | p_P2_8 | p_P2_9 | p_P2_10 | p_P2_11 | p_P2_12);
  assign P3 = p_P3_0;
  assign n_not_A0 = ~(A0);
  assign n_not_A1 = ~(A1);
  assign n_not_B0 = ~(B0);
  assign n_not_B1 = ~(B1);
  assign p_P0_0 = (A0 & n_not_A1 & B0 & n_not_B1);
  assign p_P0_1 = (A0 & n_not_A1 & B0 & B1);
  assign p_P0_2 = (A0 & A1 & B0 & n_not_B1);
  assign p_P0_3 = (A0 & A1 & B0 & B1);
  assign p_P1_0 = (n_not_A0 & n_not_A1 & n_not_B0 & n_not_B1);
  assign p_P1_1 = (n_not_A0 & n_not_A1 & n_not_B0 & B1);
  assign p_P1_2 = (n_not_A0 & n_not_A1 & B0 & n_not_B1);
  assign p_P1_3 = (n_not_A0 & n_not_A1 & B0 & B1);
  assign p_P1_4 = (n_not_A0 & A1 & n_not_B0 & n_not_B1);
  assign p_P1_5 = (n_not_A0 & A1 & n_not_B0 & B1);
  assign p_P1_6 = (A0 & n_not_A1 & n_not_B0 & n_not_B1);
  assign p_P1_7 = (A0 & n_not_A1 & B0 & n_not_B1);
  assign p_P1_8 = (A0 & A1 & n_not_B0 & n_not_B1);
  assign p_P1_9 = (A0 & A1 & B0 & B1);
  assign p_P2_0 = (n_not_A0 & n_not_A1 & n_not_B0 & n_not_B1);
  assign p_P2_1 = (n_not_A0 & n_not_A1 & n_not_B0 & B1);
  assign p_P2_10 = (A0 & A1 & n_not_B0 & n_not_B1);
  assign p_P2_11 = (A0 & A1 & B0 & n_not_B1);
  assign p_P2_12 = (A0 & A1 & B0 & B1);
  assign p_P2_2 = (n_not_A0 & n_not_A1 & B0 & n_not_B1);
  assign p_P2_3 = (n_not_A0 & n_not_A1 & B0 & B1);
  assign p_P2_4 = (n_not_A0 & A1 & n_not_B0 & n_not_B1);
  assign p_P2_5 = (n_not_A0 & A1 & B0 & n_not_B1);
  assign p_P2_6 = (A0 & n_not_A1 & n_not_B0 & n_not_B1);
  assign p_P2_7 = (A0 & n_not_A1 & n_not_B0 & B1);
  assign p_P2_8 = (A0 & n_not_A1 & B0 & n_not_B1);
  assign p_P2_9 = (A0 & n_not_A1 & B0 & B1);
  assign p_P3_0 = (A0 & A1 & B0 & B1);

endmodule
